// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: operation_types.sql

package models

import (
	"context"
)

const getOperationTypeAmountBehavior = `-- name: GetOperationTypeAmountBehavior :one
SELECT amount_behavior FROM public.operation_types WHERE serial_id = $1
`

func (q *Queries) GetOperationTypeAmountBehavior(ctx context.Context, serialID int64) (AmountBehavior, error) {
	row := q.db.QueryRow(ctx, getOperationTypeAmountBehavior, serialID)
	var amount_behavior AmountBehavior
	err := row.Scan(&amount_behavior)
	return amount_behavior, err
}
