// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users.sql

package models

import (
	"context"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM public.users WHERE uuid = $1) AS exists
`

func (q *Queries) UserExists(ctx context.Context, uuid string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
